place_labels = [
        ["LotteWorld","롯데월드"],
        ["Polky","폴키"],
        ["Onion","어니언 안국점"],
        ["Byeolmadang","별마당도서관"],
        ["Rolypolycotto", "롤리폴리꼬또"],
        ["Seoulism", "서울리즘"],
        ['SnuEntrance',"서울대학교 관악캠퍼스"],
        ['Artmonster', "아트몬스터 강남역점"],
        ['Sayu',"사유"],
        ['Seoulangmusae',"서울앵무새"],
        ['Eagle',"독수리다방"],
        ['Enuf',"이너프"],
        ['GrassFactory',"잔디공장"],
        ['DandDJeju',"디앤디파트먼트 제주"],
        ['YongmaLand',"용마랜드"],
        ['Hado',"하도미술관"],
        ['Teshphone',"테쉬폰"],
        ['Changccomrock',"창꼼"],
        ['Grandswing',"섭지코지 그네"],
        ['Vekecafe',"베케"],
        ['Rainbowroad',"도두동무지개해안도로"],
        ['Horse',"이호테우 말등대"],
        ['OlympicTree',"올림픽공원 나홀로나무"],
        ['CafeDongbaek',"카페 동백"],
        ['TheContainerJeju',"더콘테나"],
        ['Azulejo',"아줄레주"],
        ['ViewstJeju',"뷰스트"],
        ['Seogjojeon',"덕수궁 석조전"],
        ['Molto',"몰토 에스프레소 바"],
        ['BusanChurch',"드림오픈세트장"],
        ['JeonJuChurch',"전동성당"],
        ['Everland',"에버랜드"]
]

place_labels.sort(key=lambda x: x[0])